name: Update Credly badges

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main

