name: Update Credly badges

on:
  schedule:
    # Runs at 0am UTC every day
    - cron: "*/1 * * * *"
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main

